#==============================================================
#
#  Abs: Generate Archive list for all Facilities
#
#  Facility: Personnel Protection System Controls
#
#  Auth: 13-Dec-2016, Kristi Luchini  (USERNAME)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        15-Oct-2018, K. Luchini      (LUCHINI):
#          chg RULES to RULES_DIR 
#          replace files to install with dirs to build
#        04-Jun-2018, K. Luchini      (LUCHINI):
#          install sioc-in10-pp01.archive
#          install archive template for iocAdmin
#
#============================================================== 
#
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
DIRS += common lcls

include $(TOP)/configure/RULES_DIRS
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


