#==============================================================
#
#  Abs: Generate Archive list for LCLS IOCs
#
#  Facility: Personnel Protection System Controls
#
#  Auth: 13-Dec-2016, Kristi Luchini  (USERNAME)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        15-Oct-2018, K. Luchini      (LUCHINI):
#          move from odmApp/srcArchive to odmApp/srcArchive/common
#          chg gunb file name to conform to standard such that
#          the archive file is the ioc file name, lower case.
#        04-Jun-2018, K. Luchini      (LUCHINI):
#          install sioc-in10-pp01.archive
#          install archive template for iocAdmin
#
#============================================================== 
#
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
# Install archive list into $TOP/archive
ARCHIVE += sioc-cp00-od01.archive
ARCHIVE += sioc-sys0-od02.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


